<?php
$title = 'Add new job';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the name element:
$job = $form->get('name');
$job->setAttribute('class', 'form-control');
$job->setAttribute('placeholder', 'Job Name');

// This provides a default CSS class and placeholder text for the description element:
$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');

// This provides a default CSS class and placeholder text for the comapny element:
$company = $form->get('company');
$company->setAttribute('class', 'form-control');
$company->setAttribute('placeholder', 'Company');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('task3', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($job) ?>
    <?= $this->formElement($job) ?>
    <?= $this->formElementErrors()->render($job, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($company) ?>
    <?= $this->formElement($company) ?>
    <?= $this->formElementErrors()->render($company, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();