<?php
$title = 'Export jobs';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class for the type element:
$type = $form->get('type');
$type->setAttribute('class', 'form-control');

// This provides a default CSS class and placeholder text for the email element:
$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'E-mail Address');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('task3', ['action' => 'export']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($type) ?>
    <?= $this->formElement($type) ?>
    <?= $this->formElementErrors()->render($type, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->form()->closeTag();