<?php
$title = 'Add new student';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the firstname element:
$firstname = $form->get('firstname');
$firstname->setAttribute('class', 'form-control');
$firstname->setAttribute('placeholder', 'First Name');

// This provides a default CSS class and placeholder text for the lastname element:
$lastname = $form->get('lastname');
$lastname->setAttribute('class', 'form-control');
$lastname->setAttribute('placeholder', 'Last Name');

// This provides a default CSS class and placeholder text for the class element:
$class = $form->get('class_id');
$class->setAttribute('class', 'form-control');
$class->setAttribute('placeholder', 'Class');

$grade = $form->get('grade');
$grade->setAttribute('class', 'form-control');
$grade->setAttribute('placeholder', 'Grade');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('task2', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($firstname) ?>
    <?= $this->formElement($firstname) ?>
    <?= $this->formElementErrors()->render($firstname, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($lastname) ?>
    <?= $this->formElement($lastname) ?>
    <?= $this->formElementErrors()->render($lastname, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($class) ?>
    <?= $this->formElement($class) ?>
    <?= $this->formElementErrors()->render($class, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($grade) ?>
    <?= $this->formElement($grade) ?>
    <?= $this->formElementErrors()->render($grade, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();