<?php
// module/Trialday/view/trialday/task2/index.phtml:

$title = 'Students';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('task2', ['action' => 'add']) ?>">Add new student</a> | 
    <a href="<?= $this->url('task2', ['action' => 'student-average-grade']) ?>">Students Average Grade</a> | 
    <a href="<?= $this->url('task2', ['action' => 'class-average-grade']) ?>">Class Average Grade</a> | 
    <a href="<?= $this->url('task2', ['action' => 'overall-average-grade']) ?>">Overall Average Grade</a>
</p>

<table class="table">
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Class</th>
    <th>Grade</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($students as $student) : ?>
    <tr>
        <td><?= $this->escapeHtml($student->firstname) ?></td>
        <td><?= $this->escapeHtml($student->lastname) ?></td>
        <td>Class <?= $this->escapeHtml($student->class_id) ?></td>
        <td><?= $this->escapeHtml($student->grade) ?></td>
        <td>
            <a href="<?= $this->url('task2', ['action' => 'edit', 'id' => $student->id]) ?>">Edit</a>
            <a href="<?= $this->url('task2', ['action' => 'delete', 'id' => $student->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>