<?php
// module/Trialday/view/trialday/task2/student-average-grade.phtml:

$title = 'Students Average Grade';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('task2', ['action' => 'add']) ?>">Add new student</a> | 
    <a href="<?= $this->url('task2', ['action' => 'class-average-grade']) ?>">Class Average Grade</a> | 
    <a href="<?= $this->url('task2', ['action' => 'overall-average-grade']) ?>">Overall Average Grade</a>
</p>

<table class="table">
<tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Average Grade</th>
</tr>
<?php foreach ($students as $student) : ?>
    <tr>
        <td><?= $this->escapeHtml($student->firstname) ?></td>
        <td><?= $this->escapeHtml($student->lastname) ?></td>
        <td><?= $this->escapeHtml($student->average_grade) ?></td>
    </tr>
<?php endforeach; ?>
</table>